xcopy .\Assets\RsoCS\Balance\*.cs ..\Server\RsoCS\Balance\ /Y
xcopy .\Assets\RsoCS\Balance_LC\*.cs ..\Server\RsoCS\Balance_LC\ /Y
xcopy .\Assets\RsoCS\Balance_RR\*.cs ..\Server\RsoCS\Balance_RR\ /Y
xcopy .\Assets\RsoCS\Base\*.cs ..\Server\RsoCS\Base\ /Y
xcopy .\Assets\RsoCS\Core\*.cs ..\Server\RsoCS\Core\ /Y
xcopy .\Assets\RsoCS\Crypto\*.cs ..\Server\RsoCS\Crypto\ /Y
xcopy .\Assets\RsoCS\Game\*.cs ..\Server\RsoCS\Game\ /Y
xcopy .\Assets\RsoCS\GameUtil\*.cs ..\Server\RsoCS\GameUtil\ /Y
xcopy .\Assets\RsoCS\Google\*.cs ..\Server\RsoCS\Google\ /Y
xcopy .\Assets\RsoCS\Http\*.cs ..\Server\RsoCS\Http\ /Y
xcopy .\Assets\RsoCS\Math\*.cs ..\Server\RsoCS\Math\ /Y
xcopy .\Assets\RsoCS\Mobile\*.cs ..\Server\RsoCS\Mobile\ /Y
xcopy .\Assets\RsoCS\Monitor\*.cs ..\Server\RsoCS\Monitor\ /Y
xcopy .\Assets\RsoCS\Net\*.cs ..\Server\RsoCS\Net\ /Y
xcopy .\Assets\RsoCS\Physics\*.cs ..\Server\RsoCS\Physics\ /Y
xcopy .\Assets\RsoCS\Proto\*.cs ..\Server\RsoCS\Proto\ /Y
xcopy .\Assets\RsoCS\Unity\*.cs ..\Server\RsoCS\Unity\ /Y

xcopy .\Assets\RsoUnity\*.cs ..\Server\RsoUnity\Assets\RsoUnity\ /Y/S
